### ISSUE TITLE
Org token support

### ISSUE THREAD

**Issue by meagancojocar** [pulumi/pulumi-pulumiservice#15]
## Issue details

Support creating an org token and deleting an org token in the Pulumi Service provider. 

~~Note: The org token work is planned to ship 04/28 so this has a dependency on that.~~ This is now shipped!

**Comment by mchaynes** [comment]
I think we have two options for how we want to implement this.

1. Create a `OrgAccessToken` resource.
```yaml
accessToken:
  type: pulumiservice:OrgAccessToken
  properties:
    description: github-action-token
```
2. Add a field to `AccessToken` resource that specifies the type of token.
```yaml
accessToken:
  type: pulumiservice:AccessToken
  properties:
    description: github-action-token
    tokenType: "organization" # or "personal"
```
### Option 1
**Pros:**
1. Simple ux if users understand the difference between org tokens and personal access tokens.
2. Code is very simple to write, no conditionals necessary.

**Cons:**
1. Duplication of types. There's no inherent difference in usage between an org token and a personal token.
2. If you wanted to have a program that could use a personal access token **or** an org token, it would require the user to write an `if` statement. This also means you couldn't easily reproduce in YAML.

### Option 2
**Pros:**
1. No duplication of types
2. Embedding the optional logic of "org token" or "personal token" becomes very simple as its just config in the resource itself.

**Cons:**
1. Slightly worse discoverability as creating an org token would require looking into the properties of the AccessToken resource.
2. Complicates the logic inside of the provider since we'll have to dispatch different API calls depending on token type.

### My recommendation
Option 2, because it supports the YAML use case significantly better. Also, I don't believe that the usage of an OrgAccessToken and AccessToken in a pulumi program is different enough to warrant offloading that complexity to the user.

**Comment by EvanBoyle** [comment]
These are separate API types and there is no guarantee that they won't diverge. In fact, when scoping is added for instance it will most likely only be on organization tokens. 

Ultimately, the underlying token material will be a string, so there shouldn't be any requirement to write if statements or conditionals when using these tokens.

**Comment by mchaynes** [comment]
That's fair. It may be worth determining what the shape of organization tokens and personal access tokens looks like before implementing this in the provider. I do wonder, why would we would add limitations to one token type but not another? Other providers offer scoping on personal access tokens, see [github](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) for example.  

Conditionals would not be necessary for simple implementations, however for templates that produce and consume access tokens it would be simpler from a developer experience perspective. For the below example, to switch between personal access token and organization tokens, you could simply do: `pulumi config set tokenType organization` / `pulumi config set tokenType personal`. 
```yaml
configuration:
    tokenType: 
      type: String
      default: personal
accessToken:
  type: pulumiservice:AccessToken
  properties:
    description: github-action-token
    tokenType: ${accessTokenType}
```

From what I can tell, it seems that there would be no way to reproduce this kind of DX in yaml if we implemented this resource as two separate types.
