### ISSUE TITLE
Add StackTags resource

### ISSUE THREAD

**Issue by mchaynes** [pulumi/pulumi-pulumiservice#61]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

We should add a `StackTags` resource in addition to our `StackTag` resource. Right now, we have a "StackTag" resource. This works well for adding a single stack tag, however for convenience it would be nice to define a map of stack tags in a single resource. A map would be particularly nice for YAML support, where otherwise we'd need to repeat the same keys over and over again.

```yaml
  stackTags:
    type: pulumiservice:StackTags
    properties:
      tags:
        tag1: value1
        tag2: value2
        tag3: value3
```
